### ISSUE TITLE
What about Ruby 2.1.0 support?

### ISSUE THREAD

**Issue by dpsk** [halostatue/color#13]
Trying example from documentation
```
Color::RGB.new(0x20, 0x40, 0x80)
(pry) output error: #<NoMethodError: undefined method `to_rgb' for #<Object:0x0000010186d588>>
```

I also noticed that builds on travis failing for Ruby 2.0. 

Is there are any plans or anything i can help with on this one?

**Comment by bguest** [comment]
I'm thinking this (https://github.com/halostatue/color/pull/18) may fix your issue, I'm using my branch with a rails 4.2 / ruby 2.1.5 project...

**Comment by halostatue** [comment]
Merged #18; closing this based on @bguest’s comment.
